module.exports = [
    {
        section:'街道',
        data:[
            {
                label:'五角场',
                value:'五角场街道'
            },
            {
                label:'四平路',
                value:'四平路街道'
            },
            {
                label:'江浦路',
                value:'江浦路街道'
            },
            {
                label:'控江路',
                value:'控江路街道'
            },
            {
                label:'大桥街道',
                value:'大桥街道'
            },
            {
                label:'定海路',
                value:'定海路街道'
            },
            {
                label:'江湾新城',
                value:'江湾新城街道'
            },
            {
                label:'平凉路',
                value:'平凉路街道'
            },
            {
                label:'延吉新村',
                value:'延吉新村街道'
            },
            {
                label:'殷行路',
                value:'殷行路街道'
            },
            {
                label:'长白新村',
                value:'长白新村街道'
            },
            {
                label:'五角场镇',
                value:'五角场镇街道'
            },
        ]
    },{
        section:'学段',
        data:[
            {
                label:'高中',
                value:'高中'
            },
            {
                label:'初中',
                value:'初中'
            },
            {
                label:'小学',
                value:'小学'
            },
            {
                label:'幼儿园',
                value:'幼儿园'
            },
            {
                label:'其他单位',
                value:'教育行政部门'
            },
        ]
    }
]